export const rendererShellConfig = {
  editor: {
    maxOpenChatTabs: 5,
    maxOpenPromptTabs: 8,
    tabBaseWidthPx: 260,
    tabMinWidthPx: Math.round(260 * 0.3),
  },
  storage: {
    sidebarWidthKey: 'desktop-poc.sidebar-width',
    sidebarDetailsHeightKey: 'desktop-poc.sidebar-details-height',
    sidebarDetailsCollapsedKey: 'desktop-poc.sidebar-details-collapsed',
    debugHeightKey: 'desktop-poc.debug-height',
    debugCollapsedKey: 'desktop-poc.debug-collapsed',
    debugRetentionKey: 'desktop-poc.debug-retention',
    projectTreeExpandedKey: 'desktop-poc.project-tree-expanded',
    sidebarSelectionKey: 'desktop-poc.sidebar-selection',
    sidebarActiveTabKey: 'desktop-poc.sidebar-active-tab',
    newFilesCollapsedKey: 'desktop-poc.new-files-collapsed',
    newFilesHeightKey: 'desktop-poc.new-files-height',
    downloadAutomaticallyKey: 'desktop-poc.download-automatically',
    lastBrowserOpenedKey: 'desktop-poc.last-browser-opened',
    lastActiveLocalChatKey: 'desktop-poc.last-active-local-chat',
  },
  layout: {
    minSidebarWidth: 240,
    maxSidebarWidth: 620,
    minSidebarDetailsHeight: 150,
    minDebugPanelHeight: 120,
    minNewFilesPanelHeight: 140,
    maxDebugPanelHeight: 520,
  },
  debug: {
    maxLogs: 1000,
  },
  files: {
    recentFileActivityWindowMs: 10 * 60 * 1000,
    remoteManifestFile: '.chatgpt-remote/manifest.json',
    remoteMetaDirectory: '.chatgpt-remote',
    remoteManifestPrompt: [
      'When you return a project bundle ZIP for this project, always include a manifest file at `.chatgpt-remote/manifest.json` so the client can validate and safely apply the archive automatically.',
      '',
      'Use this JSON format:',
      '```json',
      '{',
      '  "project_id": "<required-current-project-id>",',
      '  "summary": "<optional short summary of changes>",',
      '  "project_root_in_archive": "<optional relative root inside the ZIP>"',
      '}',
      '```',
      '',
      'Rules:',
      '- `project_id` is required and must match the current ChatGPT project id exactly.',
      '- `summary` is optional.',
      '- `project_root_in_archive` is optional and should point to the project root inside the ZIP when files are nested under a subdirectory.',
      '- Do not include `chat_id` in the manifest.',
    ].join('\n'),
  },
} as const;
